use_frameworks!

platform :ios, 8.0
inhibit_all_warnings!

target 'HWExtension_Example' do
  pod 'HWExtension', :path => '../'

  target 'HWExtension_Tests' do
    inherit! :search_paths
    
    #   pod list:

  end
end
